spring.application.name=Leethnut




spring.datasource.url=jdbc:postgresql://dpg-d83f4rl7vvec739cik3g-a.oregon-postgres.render.com:5432/my_datas
spring.datasource.username=my_datas_user
spring.datasource.password=ksELB4TAZjWyBVe4i7n4cyXFG9jKNPwZ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.check-template-location=false
spring.web.resources.static-locations=classpath:/static/